//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dip.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalDate
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string post { get; set; }
        public string education { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string address { get; set; }
    
        public virtual User User { get; set; }
    }
}
